services:
  front-in-vuejs:
    build: 
      dockerfile: ./front-in-vuejs/Dockerfile.dev
    restart: unless-stopped
    volumes:
      - ./front-in-vuejs:/usr/app
    command: "npm run dev -- --host"
    ports:
      - "5173:5173"
    tty: true